#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
#
# install.sh — Inland TFT35 ILI9481 (userspace framebuffer daemon) installer
#
# Builds and installs the ili9481-fb userspace daemon that drives the display
# via MMIO GPIO writes, mirroring a kernel vfb virtual framebuffer to the
# ILI9481 panel.  No kernel headers, DKMS, or custom kernel modules required.
#
# Targets: Raspberry Pi OS Trixie (Debian 13, kernel 6.12+, 64-bit)
#          Raspberry Pi 1/2/3/4/Zero/Zero 2 W (NOT Pi 5)
#
# Usage:  sudo ./install.sh [OPTIONS]

set -euo pipefail

# =====================================================================
# Defaults
# =====================================================================

ROTATE=270
FPS=30
TOUCH=0

# =====================================================================
# Argument parsing
# =====================================================================

for arg in "$@"; do
    case "$arg" in
        --rotate=*)    ROTATE="${arg#*=}" ;;
        --fps=*)       FPS="${arg#*=}" ;;
        --touch)       TOUCH=1 ;;
        --no-touch)    TOUCH=0 ;;
        --help|-h)
            echo "Usage: sudo ./install.sh [OPTIONS]"
            echo "  --rotate=DEG      Display rotation: 0, 90, 180, 270 (default: 270)"
            echo "  --fps=N           Framebuffer refresh rate (default: 30)"
            echo "  --touch           Enable XPT2046 touch (WARNING: conflicts with data bus)"
            echo "  --no-touch        Skip touch setup (default)"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            exit 1
            ;;
    esac
done

# =====================================================================
# Sanity checks
# =====================================================================

if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root: sudo ./install.sh"
    exit 1
fi

case "$ROTATE" in
    0|90|180|270) ;;
    *)
        echo "Invalid --rotate value: $ROTATE (must be 0, 90, 180, or 270)"
        exit 1
        ;;
esac

# =====================================================================
# Locate boot partition paths
# =====================================================================

OVERLAYS_DIR="/boot/overlays"
CONFIG="/boot/config.txt"
CMDLINE="/boot/cmdline.txt"
if [ -d "/boot/firmware/overlays" ]; then
    OVERLAYS_DIR="/boot/firmware/overlays"
    CONFIG="/boot/firmware/config.txt"
    CMDLINE="/boot/firmware/cmdline.txt"
fi

if [ ! -f "$CONFIG" ] || [ ! -f "$CMDLINE" ]; then
    echo "Could not find boot config files."
    echo "Expected: $CONFIG and $CMDLINE"
    exit 1
fi

# =====================================================================
# Helpers
# =====================================================================

matrix_for_rotation() {
    case "$1" in
        0)   echo "1 0 0 0 1 0 0 0 1" ;;
        90)  echo "0 1 0 -1 0 1 0 0 1" ;;
        180) echo "-1 0 1 0 -1 1 0 0 1" ;;
        270) echo "0 -1 1 1 0 0 0 0 1" ;;
    esac
}

ensure_line() {
    local file="$1" line="$2"
    grep -qxF "$line" "$file" || echo "$line" >> "$file"
}

remove_lines() {
    local file="$1"; shift
    for pattern in "$@"; do
        sed -i "$pattern" "$file"
    done
}

# =====================================================================
# Banner
# =====================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Inland TFT35 ILI9481 installer (userspace daemon)"
echo "Config:   $CONFIG"
echo "Cmdline:  $CMDLINE"
echo "Rotation: $ROTATE"
echo "FPS:      $FPS"
echo "Touch:    $([ "$TOUCH" -eq 1 ] && echo yes || echo no)"
echo

# =====================================================================
# [1/9] Install required packages
# =====================================================================

echo "[1/9] Installing required packages"
apt-get update
apt-get install -y \
    build-essential \
    fbset \
    xserver-xorg-video-fbdev \
    xserver-xorg-input-evdev \
    xinput

# =====================================================================
# [2/9] Build and install ili9481-fb userspace daemon
# =====================================================================

echo "[2/9] Building and installing ili9481-fb daemon"

if [ ! -f "${SCRIPT_DIR}/src/core/service_main.c" ]; then
    echo "Error: source not found at ${SCRIPT_DIR}/src/core/service_main.c"
    exit 1
fi

make -C "${SCRIPT_DIR}" clean 2>/dev/null || true
make -C "${SCRIPT_DIR}" ENABLE_TOUCH=${TOUCH}
make -C "${SCRIPT_DIR}" install

# =====================================================================
# [3/9] Write runtime configuration
# =====================================================================

echo "[3/9] Writing runtime configuration"

mkdir -p /etc/ili9481

cat > /etc/ili9481/ili9481.conf <<EOF
# ILI9481 userspace framebuffer daemon configuration
# Generated by install.sh on $(date)

[display]
rotation = ${ROTATE}
fps = ${FPS}
fb_device = /dev/fb1

[touch]
enable_touch = ${TOUCH}
spi_device = /dev/spidev0.1
spi_speed = 2000000
EOF

# =====================================================================
# [4/9] Configure vfb module autoload
# =====================================================================

echo "[4/9] Configuring vfb module autoload"

# Compute framebuffer size based on rotation
case "$ROTATE" in
    90|270)
        FB_W=480; FB_H=320 ;;
    *)
        FB_W=320; FB_H=480 ;;
esac

cat > /etc/modprobe.d/vfb-ili9481.conf <<EOF
# Virtual framebuffer for ILI9481 display
options vfb vfb_enable=1 videomemorysize=$((FB_W * FB_H * 2))
EOF

cat > /etc/modules-load.d/inland-tft35.conf <<'EOF'
vfb
EOF

# =====================================================================
# [5/9] Clean stale config entries from previous kernel-module installs
# =====================================================================

echo "[5/9] Cleaning old config entries"

# Remove old kernel module / DTS overlay entries
remove_lines "$CONFIG" \
    '/^# Inland TFT35 SPI display/d' \
    '/^# Inland TFT35 ILI9481 display/d' \
    '/^# BEGIN inland-tft35$/,/^# END inland-tft35$/d' \
    '/^dtoverlay=piscreen/d' \
    '/^dtoverlay=waveshare35a/d' \
    '/^dtoverlay=ili9481/d' \
    '/^dtoverlay=inland-ili9481-overlay/d' \
    '/^dtoverlay=ads7846,/d' \
    '/^dtoverlay=xpt2046,/d' \
    '/^disable_fw_kms_setup=1/d'

# Remove old fbcon= mapping from cmdline (vfb doesn't need it)
sed -i 's/ fbcon=map:[^ ]*//g'  "$CMDLINE"
sed -i 's/  */ /g'              "$CMDLINE"
sed -i 's/[[:space:]]*$//'      "$CMDLINE"

# Restore KMS lines that old installer may have commented out
# (vfb is fully KMS-compatible — no need to disable KMS)
sed -i 's/^#\(dtoverlay=vc4-kms-v3d\)/\1/'     "$CONFIG"
sed -i 's/^#\(dtoverlay=vc4-fkms-v3d\)/\1/'    "$CONFIG"
sed -i 's/^#\(display_auto_detect=1\)/\1/'      "$CONFIG"

# Remove old DTS overlay artifacts
rm -f "${OVERLAYS_DIR}/inland-ili9481-overlay.dtbo"
rm -f "${OVERLAYS_DIR}/inland-ili9481-overlay.dts"

# Remove old kernel module autoload
if [ -f /etc/modules-load.d/inland-tft35.conf ]; then
    sed -i '/^ili9481-gpio$/d' /etc/modules-load.d/inland-tft35.conf
    sed -i '/^ads7846$/d' /etc/modules-load.d/inland-tft35.conf
fi

# =====================================================================
# [6/9] Install systemd service
# =====================================================================

echo "[6/9] Installing systemd service"

# Stop old services if running
systemctl disable --now ili9481-fb.service >/dev/null 2>&1 || true
systemctl disable --now inland-tft35-boot.service >/dev/null 2>&1 || true

# Install the new daemon service
cp "${SCRIPT_DIR}/systemd/ili9481-fb.service" /etc/systemd/system/

systemctl daemon-reload
systemctl enable ili9481-fb.service

# =====================================================================
# [7/9] X11 framebuffer and touch configuration
# =====================================================================

echo "[7/9] Installing X11 framebuffer and touch configuration"

mkdir -p /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/99-inland-fbdev.conf <<'EOF'
Section "Device"
    Identifier "InlandILI9481"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection
EOF

TOUCH_MATRIX="$(matrix_for_rotation "$ROTATE")"
if [ "$TOUCH" -eq 1 ]; then
    cat > /etc/X11/xorg.conf.d/99-inland-touch.conf <<EOF
Section "InputClass"
    Identifier "InlandTouch"
    MatchProduct "ILI9481 Touch"
    Driver "evdev"
    Option "CalibrationMatrix" "${TOUCH_MATRIX}"
    Option "EmulateThirdButton" "true"
EndSection
EOF
else
    rm -f /etc/X11/xorg.conf.d/99-inland-touch.conf
fi

# =====================================================================
# [8/9] Boot-time framebuffer mapping service
# =====================================================================

echo "[8/9] Enabling boot mapping service"

cat > /usr/local/bin/inland-tft35-boot <<'BOOTSCRIPT'
#!/bin/bash
set -euo pipefail

fb_number=""
for fb_dir in /sys/class/graphics/fb*; do
    [ -d "$fb_dir" ] || continue
    name_file="${fb_dir}/name"
    [ -f "$name_file" ] || continue
    if grep -qi 'Virtual FB\|vfb' "$name_file"; then
        fb_number="$(basename "$fb_dir" | sed 's/fb//')"
        break
    fi
done

if [ -z "$fb_number" ]; then
    exit 0
fi

if command -v con2fbmap >/dev/null 2>&1; then
    for vt in 1 2 3 4 5 6; do
        con2fbmap "$vt" "$fb_number" >/dev/null 2>&1 || true
    done
fi

if [ -f /etc/X11/xorg.conf.d/99-inland-fbdev.conf ]; then
    sed -i "s#Option \"fbdev\" \"/dev/fb[0-9]*\"#Option \"fbdev\" \"/dev/fb${fb_number}\"#" \
        /etc/X11/xorg.conf.d/99-inland-fbdev.conf
fi
BOOTSCRIPT
chmod 755 /usr/local/bin/inland-tft35-boot

cat > /etc/systemd/system/inland-tft35-boot.service <<'EOF'
[Unit]
Description=Inland TFT35 framebuffer mapper
After=systemd-modules-load.service
Before=display-manager.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/inland-tft35-boot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable inland-tft35-boot.service

# =====================================================================
# [9/9] Switch to X11 if using Wayland
# =====================================================================

echo "[9/9] Checking desktop backend"

if command -v raspi-config >/dev/null 2>&1; then
    WAYLAND_STATE="$(raspi-config nonint get_wayland 2>/dev/null || echo unknown)"
    if [ "$WAYLAND_STATE" = "0" ]; then
        raspi-config nonint do_wayland W1 || true
    fi
fi

# =====================================================================
# Done
# =====================================================================

echo
echo "Install complete."
echo "  Binary:  /usr/local/bin/ili9481-fb"
echo "  Config:  /etc/ili9481/ili9481.conf"
echo "  Service: ili9481-fb.service"
echo
echo "Reboot now: sudo reboot"
